/*jshint maxlen:false */

define({
    ACTION:                             "アクション",
    ADD_ENDLINE_TO_THE_END_OF_FILE:     "ファイルの終端に改行を加える",
    ADD_TO_GITIGNORE:                   ".gitignore に追加",
    ADVANCED_FEATURES_WARNING:          "この機能はGit 上級者向けです。誤操作により、既にコミットしたコードが失われる可能性があります。慎重に操作して下さい。",
    AMEND_COMMIT:                       "最後のコミットを修正する (--amend)",
    AMEND_COMMIT_FORBIDDEN:             "push されていないコミットがない時には、コミットの修正 (amend) はできません。",
    _ANOTHER_BRANCH:                    "another branch",
    AUTHOR:                             "作者",
    AUTHORS_OF:                         "Authors of",
    AVATAR_TYPE:                        "アバターのタイプ",
    BASH_NOT_AVAILABLE:                 "Bash が利用できないか、適切に設定されていません。",
    BASIC_CONFIGURATION:                "基本設定",
    BLACK_WHITE_AVATAR:                 "白黒アバター",
    BRACKETS_GIT_ERROR:                 "Brackets Git においてエラーが発生しました。\u2026",
    BRANCH_NAME:                        "ブランチ名",
    BUTTON_CANCEL:                      "キャンセル",
    BUTTON_CHANGELOG:                   "変更履歴を表示",
    BUTTON_CHECKOUT_COMMIT:             "チェックアウト",
    BUTTON_CLONE:                       "クローン",
    BUTTON_CLOSE:                       "閉じる",
    BUTTON_COMMIT:                      "コミット",
    BUTTON_DEFAULTS:                    "初期設定に戻す",
    BUTTON_FIND_CONFLICTS:              "Find conflicts\u2026",
    BUTTON_INIT:                        "リポジトリーの作成 (init)",
    BUTTON_MERGE_ABORT:                 "マージを中止",
    BUTTON_OK:                          "OK",
    BUTTON_REBASE_ABORT:                "キャンセル (abort)",
    BUTTON_REBASE_CONTINUE:             "続行 (continue)",
    BUTTON_REBASE_SKIP:                 "スキップ (skip)",
    BUTTON_REPORT:                      "Report",
    BUTTON_RESET:                       "Reset index",
    BUTTON_RESET_HARD:                  "Reset to this commit and discard the changes that came after it. (reset --hard)",
    BUTTON_RESET_MIXED:                 "Reset to this commit and retain changes that came after it unstaged. (reset --mixed)",
    BUTTON_RESET_SOFT:                  "Reset to this commit and retain changes that came after it staged for a new commit. (reset --soft)",
    BUTTON_SAVE:                        "保存",
    CANCEL:                             "キャンセル",
    CHANGELOG:                          "変更履歴",
    CHANGE_USER_EMAIL:                  "git email を変更",
    CHANGE_USER_NAME:                   "git username を変更",
    CHECK_GIT_SETTINGS:                 "Git の起動に失敗しました。Git の設定を修正し、Brackets を再起動して下さい。",
    CLEAN_FILE_END:                     "File cleaned",
    CLEAN_FILE_START:                   "Cleaning file",
    CLEANING_WHITESPACE_PROGRESS:       "ファイル中のスペースを除去しています。\u2026",
    CLEAR_WHITESPACE_ON_FILE_SAVE:      "ファイル保存時にスペースを削除",
    CLONE_REPOSITORY:                   "リポジトリーをクローン",
    CODE_INSPECTION_PROBLEMS:           "Code inspection problems:",
    COLLAPSE_ALL:                       "全て閉じる",
    COLORED_AVATAR:                     "Colored avatar",
    COMMAND_ARGUMENTS:                  "Command arguments",
    COMMIT:                             "コミット",
    COMMIT_ALL_SHORTCUT:                "全てのファイルをコミット",
    COMMIT_CURRENT_SHORTCUT:            "現在のファイルをコミット",
    COMMIT_MESSAGE_PLACEHOLDER:         "コミットメッセージをここに記述して下さい\u2026",
    CREATE_NEW_BRANCH:                  "新規ブランチ\u2026",
    CREATE_NEW_GITFTP_SCOPE:            "Create new Git-FTP remote\u2026",
    CREATE_NEW_REMOTE:                  "新規リモートリポジトリー\u2026",
    CURRENT_TRACKING_BRANCH:            "Current tracking branch",
    _CURRENT_TRACKING_BRANCH:           "current tracking branch",
    CUSTOM_TERMINAL_COMMAND:            "Custom terminal command (sample: gnome-terminal or complete path to executable)",
    CUSTOM_TERMINAL_COMMAND_HINT:       "Sample arguments: --window --working-directory=$1<br>$1 in arguments will be replaced by current project directory.",
    DATE_FORMAT:                        "MM/DD/YYYY HH:mm:ss",
    DATE_MODE_0:                        "Formatted using local date format",
    DATE_MODE_1:                        "Relative time",
    DATE_MODE_2:                        "Intelligent mode (relative/formatted)",
    DATE_MODE_3:                        "Formatted using your own format",
    DATE_MODE_4:                        "Original Git date",
    DEBUG:                              "デバッグ",
    DEBUG_MODE_SETTING:                 "DEBUG mode &mdash; Leave this OFF unless you need to find a problem with the extension. All Git communication will be forwarded to Brackets console!",
    DEFAULT_GIT_TIMEOUT:                "Default Git operation timeout (in seconds)",
    DELETE_FILE:                        "ファイルを削除",
    DELETE_LOCAL_BRANCH:                "ローカルブランチを削除",
    DELETE_LOCAL_BRANCH_NAME:           "本当にローカルブランチ \"{0}\" を削除しますか?",
    DELETE_REMOTE:                      "リモートリポジトリーを削除",
    DELETE_REMOTE_NAME:                 "本当にリモートリポジトリー \"{0}\" を削除しますか?",
    DELETE_SCOPE:                       "Delete Git-FTP scope",
    DELETE_SCOPE_NAME:                  "Do you really wish to delete Git-FTP scope \"{0}\"?",
    DIALOG_CHECKOUT:                    "When checking out a commit, the repo will go into a DETACHED HEAD state. You can't make any commits unless you create a branch based on this.",
    DIALOG_PULL_TITLE:                  "リモートリポジトリーから pull する",
    DIALOG_PUSH_TITLE:                  "リモートリポジトリーに push する",
    DIALOG_RESET_HARD:                  "You will lose all changes after this commit!",
    DIALOG_RESET_MIXED:                 "Changes after this commit will be unstaged.",
    DIALOG_RESET_SOFT:                  "Changes after this commit will be staged for a new commit.",
    DIFF:                               "Diff",
    DIFFTOOL:                           "Diff with difftool",
    DIFF_FAILED_SEE_FILES:              "Git diff failed to provide diff results. This is the list of staged files to be commited:",
    DIFF_TOO_LONG:                      "Diff too long to display",
    ENABLE_ADVANCED_FEATURES:           "Enable advanced features",
    ENABLE_GERRIT_PUSH_REF:             "Use Gerrit-compatible push ref",
    ENTER_GITFTP_SCOPE_NAME:            "Enter name of the new Git-FTP remote:",
    ENTER_GITFTP_SCOPE_URL:             "Enter FTP URL of the new Git-FTP remote specifing username and password:",
    ENTER_NEW_USER_EMAIL:               "Enter email",
    ENTER_NEW_USER_NAME:                "Enter username",
    ENTER_PASSWORD:                     "Enter password:",
    ENTER_REMOTE_GIT_URL:               "Enter Git URL of the repository you want to clone:",
    ENTER_REMOTE_NAME:                  "Enter name of the new remote:",
    ENTER_REMOTE_URL:                   "Enter URL of the new remote:",
    ENTER_USERNAME:                     "Enter username:",
    ERROR_CONNECT_NODEJS:               "Failed to connect to NodeJS. If you've just updated the extension then close all instances of Brackets and try starting again. If restart doesn't help try removing other extensions that you've installed as one of them is probably causing this problem.",
    ERROR_NOTHING_SELECTED:             "Nothing is selected!",
    ERROR_SAVE_FIRST:                   "Save the document first!",
    ERROR_TERMINAL_NOT_FOUND:           "Terminal was not found for your OS, you can define a custom Terminal command in the settings",
    EXPAND_ALL:                         "Expand all",
    EXTENDED_COMMIT_MESSAGE:            "EXTENDED",
    EXTENSION_WAS_UPDATED_TITLE:        "The extension was updated to {0}",
    FEATURES:                           "Features",
    FILE_ADDED:                         "New file",
    FILE_COPIED:                        "Copied",
    FILE_DELETED:                       "Deleted",
    FILE_IGNORED:                       "Ignored",
    FILE_MODIFIED:                      "Modified",
    FILE_RENAMED:                       "Renamed",
    FILE_STAGED:                        "Staged",
    FILE_UNMERGED:                      "Unmerged",
    FILE_UNMODIFIED:                    "Unmodified",
    FILE_UNTRACKED:                     "Untracked",
    FOR_MAC_LINUX_USERS:                "For Mac/Linux users",
    FOR_WINDOWS_USERS:                  "For Windows users",
    GETTING_STAGED_DIFF_PROGRESS:       "Getting diff of staged files\u2026",
    GITFTP_PUSH_RESPONSE:               "Git-FTP Push response",
    GITFTP_SCOPES:                      "Git-FTP remotes",
    GIT_COMMIT:                         "Git commit\u2026",
    GIT_CONFIGURATION:                  "Git configuration",
    GIT_DIFF:                           "Git diff &mdash;",
    GIT_PULL_RESPONSE:                  "Git Pull response",
    GIT_PUSH_RESPONSE:                  "Git Push response",
    GIT_REMOTES:                        "Git remotes",
    GIT_SETTINGS:                       "Git Settings\u2026",
    GOTO_NEXT_GIT_CHANGE:               "Go to next Git change",
    GOTO_PREVIOUS_GIT_CHANGE:           "Go to previous Git change",
    GUTTER_CLICK_DETAILS:               "Click for more details",
    HIDE_UNTRACKED:                     "Hide untracked",
    HISTORY:                            "History",
    HISTORY_COMMIT_BY:                  "by",
    IDENTICON:                          "Identicon (www.gravatar.com)",
    INIT_GITFTP_SCOPE:                  "Initialize Git-FTP remote",
    INIT_GITFTP_SCOPE_NAME:             "Initialize Git-FTP remote \"{0}\"?",
    LAUNCH_BASH_SHORTCUT:               "Bash/Terminal shortcut",
    LINES:                              "Lines",
    _LINES:                             "lines",
    LIST_MODIFIED_FILES:                "Modified files",
    LOADING:                            "Loading\u2026",
    MARK_MODIFIED_FILES_IN_TREE:        "Mark modified files in file tree",
    MERGE_BRANCH:                       "Merge branch",
    MERGE_MESSAGE:                      "Merge message",
    MERGE_RESULT:                       "Merge result",
    MORE_INFO:                          "More information\u2026",
    NORMALIZE_LINE_ENDINGS:             "Normalize line endings (to \\n)",
    NOTHING_TO_COMMIT:                  "Nothing to commit, working directory clean.",
    OK:                                 "OK",
    OPERATION_IN_PROGRESS_TITLE:        "Git operation in progress\u2026",
    ORIGIN_BRANCH:                      "Origin branch",
    PANEL_COMMAND:                      "Show Git panel",
    PANEL_SHORTCUT:                     "Toggle panel",
    PASSWORD:                           "Password",
    PASSWORDS:                          "Passwords",
    PATH_TO_GIT_EXECUTABLE:             "Path to Git executable",
    PATH_TO_GIT_MSYSGIT:                "Path to msysgit folder",
    PICTURE:                            "Gravatar (www.gravatar.com)",
    PULL_AVOID_MERGING:                 "Avoid manual merging",
    PULL_DEFAULT:                       "Default merge",
    PULL_FROM:                          "Pull from",
    PULL_MERGE_NOCOMMIT:                "Merge without commit",
    PULL_REBASE:                        "Use rebase",
    PULL_RESET:                         "Use soft reset",
    PULL_SHORTCUT:                      "Pull from remote repository",
    PUSH_DEFAULT:                       "Default push",
    PUSH_DELETE_BRANCH:                 "Delete remote branch",
    PUSH_FORCED:                        "Forced push",
    PUSH_SHORTCUT:                      "Push to remote repository",
    PUSH_TO:                            "Push to",
    Q_DELETE_FILE:                      "Are you sure you wish to delete the file <span class='dialog-filename'>{0}</span>?",
    Q_RESTART_BRACKETS:                 "Do you wish to restart Brackets to apply new settings?",
    Q_UNDO_CHANGES:                     "Reset changes to file <span class='dialog-filename'>{0}</span>?",
    REBASE_RESULT:                      "Rebase result",
    REMOVE_BOM:                         "Remove BOM from files",
    REMOVE_FROM_GITIGNORE:              "Remove from .gitignore",
    REQ_INTERNET:                       "Requires internet connection",
    RESET_LOCAL_REPO:                   "Discard all changes since last commit",
    RESET_LOCAL_REPO_CONFIRM:           "Do you wish to discard all changes done since last commit? This action can't be reverted.",
    RESTART:                            "再起動",
    SAVE_CREDENTIALS_HELP:              "You don't need to fill out username/password if your credentials are managed elsewhere. Use this only when your operation keeps timing out.",
    SAVE_CREDENTIALS_IN_URL:            "Save credentials to remote url (in plain text)",
    SAVE_PASSWORD_QUESTION:             "Save username/password?",
    SET_ORIGIN_URL:                     "Set origin URL",
    SET_THIS_BRANCH_AS_TRACKING:        "Set this branch as a new tracking branch",
    SHORTCUTS:                          "Shortcuts",
    SHORTCUTS_HINT:                     "Separate keys with dash, like this: Ctrl-Alt-G<br>You can use the english key identifiers Ctrl, Cmd (Mac), Alt and Shift.",
    SHOWN_DATE_FORMAT:                  "Format of commit dates in history",
    SHOW_BASH_TERMINAL_BUTTON:          "Show Bash/Terminal button in the panel",
    SHOW_REPORT_BUG_BUTTON:             "Show Report Bug button in the panel",
    SHOW_TERMINAL_IN_TOOLBAR:           "Show Terminal icon in toolbar",
    SHOW_UNTRACKED:                     "Show untracked",
    STRIP_WHITESPACE_FROM_COMMITS:      "Strip trailing whitespace from commits",
    TARGET_BRANCH:                      "Target branch",
    TERMINAL_DISABLED:                  "Bash/Terminal console is disabled because no valid executable was found",
    TITLE_CHECKOUT:                     "Do you really wish to checkout this commit?",
    TITLE_RESET:                        "Do you really wish to reset?",
    TOOLTIP_BUG:                        "Report bug",
    TOOLTIP_CHECKOUT_COMMIT:            "Checkout a specific commit",
    TOOLTIP_CLONE:                      "Clone existing repository",
    TOOLTIP_CLOSE_NOT_MODIFIED:         "Close files not modified in Git [Shift-click to reopen modified files]",
    TOOLTIP_COMMIT:                     "Commit the selected files",
    TOOLTIP_FIND_CONFLICTS:             "Starts a search for Git merge/rebase conflicts in the project",
    TOOLTIP_GITPUSH:                    "Git-FTP Push",
    TOOLTIP_HIDE_FILE_HISTORY:          "Hide file history",
    TOOLTIP_HIDE_HISTORY:               "Hide history",
    TOOLTIP_INIT:                       "Initialize repository",
    TOOLTIP_MERGE_ABORT:                "Abort the merge operation and reset HEAD to the last local commit",
    TOOLTIP_MORE:                       "More actions\u2026",
    TOOLTIP_OPEN_BASH:                  "Open Bash/Terminal console",
    TOOLTIP_PICK_REMOTE:                "Pick preferred remote",
    TOOLTIP_PULL:                       "Git Pull",
    TOOLTIP_PUSH:                       "Git Push",
    TOOLTIP_REBASE_ABORT:               "Abort the rebase operation and reset HEAD to the original branch",
    TOOLTIP_REBASE_CONTINUE:            "Restart the rebasing process after having resolved a merge conflict",
    TOOLTIP_REBASE_SKIP:                "Restart the rebasing process by skipping the current patch",
    TOOLTIP_REFRESH_PANEL:              "パネルの更新Refresh panel",
    TOOLTIP_SHOW_FILE_HISTORY:          "ファイルの変更履歴を表示",
    TOOLTIP_SHOW_HISTORY:               "履歴を表示",
    UNDO_CHANGES:                       "変更を破棄",
    UNDO_LAST_LOCAL_COMMIT:             "最後のローカル (未 push の) コミットを戻す",
    URL:                                "URL",
    USERNAME:                           "ユーザー名",
    USER_ABORTED:                       "User aborted!",
    USER_DATE_FORMAT:                   "Own date format (<a href='http://momentjs.com/docs/#/displaying/format/'>Syntax</a>)",
    USE_CODE_INSPECTION:                "Use Code inspection",
    USE_GITFTP:                         "Git-FTP を使う",
    USE_GIT_GUTTER:                     "Use Git gutter marks",
    USE_NOFF:                           "Create a merge commit even when the merge resolves as a fast-forward (--no-ff)",
    USE_REBASE:                         "REBASE を使う",
    USE_VERBOSE_DIFF:                   "Show verbose output in diffs",
    USE_DIFFTOOL:                       "差分の表示に difftool を使う",
    USING_GIT_VERSION:                  "Git バージョン",
    VIEW_AUTHORS_FILE:                  "View authors of file",
    VIEW_AUTHORS_SELECTION:             "View authors of selection",
    VIEW_THIS_FILE:                     "このファイルを表示"
});
